### ISSUE TITLE
docking branch

### ISSUE THREAD

**Issue by mwindowshz** [masc-it/pyimgui-interface-generator#1]
Sorry for this question
I found the branch of docking but don't know how to pip install this branch

Hi can you please explain how do you get the python version of imgui docking branch? I cannot find it.
pip install imgui[full] does not have the docking
and how do I use it?

and then if I understand I need to copy your special created file?

**Comment by masc-it** [comment]
Unfortunately you cannot install the pyimgui docking branch using pip.

Steps to do it, manually:
```
git clone --branch docking https://github.com/pyimgui/pyimgui
cd pyimgui
make build
```
If you have any errors, check pyimgui [docs](https://github.com/pyimgui/pyimgui).

> and then if I understand I need to copy your special created file?

Correct. Copy the .pyi into the site-packages of your venv.
